# Generated by Django 6.0.3 on 2026-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('HATCHBACK', 'Hatchback'), ('COUPE', 'Coupe'), ('MINIVAN', 'Minivan'), ('PICKUP', 'Pickup'), ('CONVERTIBLE', 'Convertible')], default='SUV', max_length=20),
        ),
    ]
